language: clojure
lein: lein2
before_install:
  - "ulimit -u 4096 && make start_one_node_cluster"
script: lein2 all do clean, test
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - 1.3.x-stable
