language: clojure
lein: lein2
before_install:
  - "ulimit -u 4096 && pip install ccm"
script: lein2 all do clean, javac, test
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - 1.3.x-stable
