language: clojure
lein: lein2
before_install:
  - "ulimit -u 4096"
script: lein2 all do clean, javac, test
services:
  - cassandra
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - 1.3.x-stable
